language: python
python:
- 3.7.1
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_1a1b9769344c_key -iv $encrypted_1a1b9769344c_iv
  -in config.py.enc -out config.py -d
- docker build -f database/Dockerfile -t reminder .
script:
- docker run -d reminder
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: MSKMed
  env: Mskmed-env-1
  bucket_name: elasticbeanstalk-us-east-1-314414864449
  bucket_path: MSKMed2
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
