#test
language: python

python:
- 3.7.1

services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_1a1b9769344c_key -iv $encrypted_1a1b9769344c_iv -in database/config.py.enc -out database/config.py -d
- docker build -f database/Dockerfile -t reminder .

script:
- docker run reminder

deploy:

  provider: elasticbeanstalk

  region: us-east-1

  app: MSKMed

  env: Mskmed-env

  bucket_name: elasticbeanstalk-us-east-1-314414864449

  bucket_path: MSKMed

  on:
    branch: master

  access_key_id: "$AWS_ACCESS_KEY"
  
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
